version: 2.1

# ======================= JOBS =======================
jobs:
  gapic-generator-java-tests:
    docker:
      - image: l.gcr.io/google/bazel
    working_directory: /home/circleci/project/gapic-generator-java
    steps:
      - checkout
      - run:
          name: Builder
          command: |
            LATEST_COMMIT=$(git rev-parse HEAD)
            NUM_NOCHECKS=$(git diff-tree --no-commit-id --name-only -r $LATEST_COMMIT | grep .*.md | wc -l)
            NUM_TOTAL=$(git diff-tree --no-commit-id --name-only -r $LATEST_COMMIT | wc -l)
            if [ $NUM_NOCHECKS == $NUM_TOTAL ]
            then
              # Run build checks only if there are non-Markdown files in this change.
              bazel build //...
            fi
  google-java-format:
    docker:
      - image: l.gcr.io/google/bazel
    working_directory: /home/circleci/workspace/gapic-generator-java
    steps:
      - checkout
      - run:
          name: Java Linter
          command: |
            LATEST_COMMIT=$(git rev-parse HEAD)
            NUM_JAVA=$(git diff-tree --no-commit-id --name-only -r $LATEST_COMMIT | grep .*.java | wc -l)
            # Run Java linter checks only if there are Java files in this change.
            if [ $NUM_JAVA != 0 ]
            then
              bazel build //:google_java_format_verification
            fi

# ======================= WORKFLOWS =======================

workflows:
  version: 2
  run_tests:
    jobs:
      - gapic-generator-java-tests
      - google-java-format
